# Generated by Django 3.0.2 on 2020-01-08 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('user_sessions', '0002_auto_20200108_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersessions',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
    ]
