# Generated by Django 3.0.2 on 2020-01-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0003_auto_20200108_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersessions',
            name='session',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
